"""create tables

Revision ID: f77d15528b75
Revises: f9bd49889eea
Create Date: 2026-06-06 09:23:24.424017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f77d15528b75'
down_revision: Union[str, Sequence[str], None] = 'f9bd49889eea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for this report'),
    sa.Column('input_type', sa.String(length=10), nullable=False, comment="'url' or 'text'"),
    sa.Column('input_content', sa.Text(), nullable=False, comment='Raw URL or pasted text submitted by the user'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Current lifecycle state of the report'),
    sa.Column('company_brief', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('market_analysis', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('competitor_analysis', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('skeptic_analysis', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('assumptions', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('execution_feasibility', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('contradictions', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('synthesized_memo', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('overall_confidence_score', sa.Float(), nullable=True, comment='Aggregated confidence score (0–100)'),
    sa.Column('red_flags', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Critical issues surfaced across agents'),
    sa.Column('investment_signal', sa.String(length=20), nullable=True, comment='STRONG / MODERATE / WEAK'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='When the analysis was requested'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Last modification timestamp'),
    sa.Column('error_log', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Structured error information (if any)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assumptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False, comment='FK → reports.id'),
    sa.Column('assumption', sa.Text(), nullable=False),
    sa.Column('validation_difficulty', sa.String(length=20), nullable=False, comment='easy / moderate / hard / very_hard'),
    sa.Column('impact_if_false', sa.String(length=20), nullable=False, comment='negligible / low / moderate / high / catastrophic'),
    sa.Column('source', sa.String(length=500), nullable=False, comment='Which agent or data source surfaced this assumption'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False, comment='FK → reports.id'),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('pricing', sa.String(length=500), nullable=True),
    sa.Column('positioning', sa.String(length=500), nullable=True),
    sa.Column('strengths', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('weaknesses', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=False, comment='Where this competitor info was found'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False, comment='FK → reports.id'),
    sa.Column('risk', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False, comment='low / medium / high / critical'),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=False, comment='Which agent or data source surfaced this risk'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_breakdowns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False, comment='FK → reports.id'),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('market_opportunity', sa.Float(), nullable=False),
    sa.Column('competition_intensity', sa.Float(), nullable=False),
    sa.Column('execution_feasibility', sa.Float(), nullable=False),
    sa.Column('risk_exposure', sa.Float(), nullable=False),
    sa.Column('investment_signal', sa.String(length=20), nullable=False, comment='STRONG / MODERATE / WEAK'),
    sa.Column('justification', sa.Text(), nullable=False, comment='Plain-English explanation of the score'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score_breakdowns')
    op.drop_table('risk_analyses')
    op.drop_table('competitors')
    op.drop_table('assumptions')
    op.drop_table('reports')
    # ### end Alembic commands ###
